using BacklinkStudio.Domain;

namespace BacklinkStudio.Application;

public static class ContractMapping
{
    public static ProjectDto ToDto(this Project value) => new(value.Id, value.Name, value.PrimaryDomain, value.Description, value.Status, value.CreatedAt, value.UpdatedAt);
    public static TargetDto ToDto(this ProjectTarget value) => new(value.Id, value.ProjectId, value.Url, value.NormalizedUrl, value.Label, value.Keywords, value.PreferredAnchor, value.Category, value.Priority, value.Enabled, value.CreatedAt);
    public static OpportunityDto ToDto(this Opportunity value) => new(value.Id, value.ProjectId, value.CandidatePageId, value.Type, value.SourceUrl, value.Domain, value.QualityScore, value.RiskScore, value.AutomationStatus, value.AnalysisReason, value.ScoreReasons.Select(x => new ScoreReasonDto(x.Kind, x.Code, x.Points, x.Explanation)).ToArray(), value.DetectedAt, value.LastAnalyzedAt);
    public static CampaignDto ToDto(this Campaign value) => new(value.Id, value.ProjectId, value.Name, value.ApprovalMode, value.AuthorizationProfileKey, value.AuthorizationReference, value.DailyActionLimit, value.Status, value.CreatedAt, value.UpdatedAt);
    public static SubmissionJobDto ToDto(this SubmissionJob value) => new(value.Id, value.ProjectId, value.CampaignId, value.CampaignOpportunityId, value.PersistentJobId, value.Status, value.CreatedAt, value.UpdatedAt, value.SubmissionSourceId, value.TargetUrl, value.PlacementType);
    public static SubmissionAttemptDto ToDto(this SubmissionAttempt value) => new(value.Id, value.SubmissionJobId, value.AttemptNumber, value.Adapter, value.StartedAt, value.FinishedAt, value.Result, value.HttpStatus, value.ExternalReference, value.Error, value.PersistentJobId, value.SubmissionSourceId, value.TargetUrl, value.Strategy, value.IdentityId, value.TemplateId, value.ResolvedDisplayName, value.ResolvedEmail, value.ResolvedWebsite, value.ModerationStatus, value.FailureKind, value.Endpoint, value.RedirectDestination);
    public static BacklinkDto ToDto(this Backlink value) => new(value.Id, value.ProjectId, value.CampaignId, value.SubmissionJobId, value.SourceUrl, value.NormalizedSourceUrl, value.TargetUrl, value.NormalizedTargetUrl, value.Domain, value.Status, value.AnchorText, value.Rel, value.Nofollow, value.Ugc, value.Sponsored, value.HttpStatus, value.CanonicalUrl, value.FirstSeenAt, value.LastSeenAt, value.LastCheckedAt, value.CreatedAt, value.UpdatedAt, value.SubmissionSourceId, value.SubmissionAttemptId);
    public static VerificationCheckDto ToDto(this VerificationCheck value) => new(value.Id, value.BacklinkId, value.CheckedAt, value.Found, value.HttpStatus, value.Anchor, value.Rel, value.Error, value.DurationMilliseconds);
    public static JobDto ToDto(this PersistentJob value) => new(value.Id, value.Type, value.ProjectId, value.CampaignId, value.Status, value.Priority, value.Domain, value.CreatedAt, value.AvailableAt, value.ClaimedAt, value.ClaimExpiresAt, value.StartedAt, value.CompletedAt, value.LastHeartbeatAt, value.PauseRequestedAt, value.PausedAt, value.AttemptCount, value.MaxAttempts, value.RecoveryCount, value.LastFailureKind, value.LastError, value.CorrelationId);
    public static BlocklistEntryDto ToDto(this BlocklistEntry value) => new(value.Id, value.ProjectId, value.MatchType, value.Value, value.Reason, value.Enabled, value.CreatedAt);
    public static PolicyDefinitionDto ToDto(this PolicyDefinition value) => new(value.Id, value.ProjectId, value.AutomationEnabled, value.MinimumQualityScore, value.MaximumRiskScore, value.ManualReviewRequired, value.HourlyActionLimit, value.DailyActionLimit, value.PerDomainActionLimit, value.CreatedAt, value.UpdatedAt);
    public static DiscoveryRunDto ToDto(this DiscoveryRun value, DiscoveryQuery query) => new(value.Id, value.ProjectId, value.DiscoveryQueryId, value.JobId, query.Provider, query.QueryText, value.Status, value.UrlsDiscovered, value.UrlsAccepted, value.DuplicateCount, value.BlockedCount, value.InvalidCount, value.ErrorCount, value.Errors, value.CreatedAt, value.StartedAt, value.FinishedAt);
    public static ReportDto ToDto(this Report value) => new(value.Id, value.ProjectId, value.CampaignId, value.JobId, value.Kind, value.Format, value.Status, value.ArtifactName, value.ContentType, value.ByteLength, value.Sha256, value.RowCount, value.Error, value.CreatedAt, value.UpdatedAt, value.StartedAt, value.CompletedAt);
}
