// <auto-generated />
using System;
using BacklinkStudio.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BacklinkStudio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BacklinkStudioDbContext))]
    [Migration("20260820174930_HardenProductionOperations")]
    partial class HardenProductionOperations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BacklinkStudio.Domain.AgentCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("KeyHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key_hash");

                    b.Property<byte[]>("KeySalt")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key_salt");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("LookupHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("lookup_hash");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .IsConcurrencyToken()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("LookupHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("agent_credentials", (string)null);
                });

            modelBuilder.Entity("BacklinkStudio.Domain.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid?>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<string>("InputSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("input_summary");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operation");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("request_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("result");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_address");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("ProjectId", "Timestamp");

                    b.ToTable("audit_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_input_summary_length", "length(input_summary) <= 2000");
                        });
                });

            modelBuilder.Entity("BacklinkStudio.Domain.Backlink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnchorText")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("anchor_text");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<string>("CanonicalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("canonical_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("domain");

                    b.Property<DateTimeOffset?>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("integer")
                        .HasColumnName("http_status");

                    b.Property<DateTimeOffset?>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_checked_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<bool>("Nofollow")
                        .HasColumnType("boolean")
                        .HasColumnName("nofollow");

                    b.Property<string>("NormalizedSourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("normalized_source_url");

                    b.Property<string>("NormalizedTargetUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("normalized_target_url");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.PrimitiveCollection<string[]>("Rel")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("rel");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<bool>("Sponsored")
                        .HasColumnType("boolean")
                        .HasColumnName("sponsored");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<Guid?>("SubmissionJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_job_id");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("target_url");

                    b.Property<bool>("Ugc")
                        .HasColumnType("boolean")
                        .HasColumnName("ugc");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("LastCheckedAt");

                    b.HasIndex("SubmissionJobId")
                        .IsUnique();

                    b.HasIndex("Domain", "Status");

                    b.HasIndex("ProjectId", "NormalizedSourceUrl", "NormalizedTargetUrl")
                        .IsUnique();

                    b.HasIndex("ProjectId", "Status", "CreatedAt", "Id");

                    b.ToTable("backlinks", (string)null);
                });

            modelBuilder.Entity("BacklinkStudio.Domain.BlocklistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("match_type");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CreatedAt", "Id");

                    b.HasIndex("ProjectId", "MatchType", "Value")
                        .IsUnique();

                    b.ToTable("blocklist_entries", (string)null);
                });

            modelBuilder.Entity("BacklinkStudio.Domain.Campaign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ApprovalMode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("approval_mode");

                    b.Property<string>("AuthorizationProfileKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("authorization_profile_key");

                    b.Property<string>("AuthorizationReference")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("authorization_reference");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DailyActionLimit")
                        .HasColumnType("integer")
                        .HasColumnName("daily_action_limit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CreatedAt", "Id");

                    b.ToTable("campaigns", null, t =>
                        {
                            t.HasCheckConstraint("ck_campaign_daily_limit", "daily_action_limit BETWEEN 1 AND 100000");
                        });
                });

            modelBuilder.Entity("BacklinkStudio.Domain.CampaignOpportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("ExplicitlyApproved")
                        .HasColumnType("boolean")
                        .HasColumnName("explicitly_approved");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId");

                    b.HasIndex("CampaignId", "OpportunityId")
                        .IsUnique();

                    b.ToTable("campaign_opportunities", (string)null);
                });

            modelBuilder.Entity("BacklinkStudio.Domain.CampaignTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProjectTargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_target_id");

                    b.HasKey("Id");

                    b.HasIndex("ProjectTargetId");

                    b.HasIndex("CampaignId", "ProjectTargetId")
                        .IsUnique();

                    b.ToTable("campaign_targets", (string)null);
                });

            modelBuilder.Entity("BacklinkStudio.Domain.CandidatePage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnalysisError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("analysis_error");

                    b.Property<string>("AnalysisStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("analysis_status");

                    b.Property<Guid>("CandidateSiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_site_id");

                    b.Property<string>("CanonicalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("canonical_url");

                    b.Property<string>("Cms")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cms");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<string[]>("EligibleSignals")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("eligible_signals");

                    b.Property<bool>("ExistingTargetLink")
                        .HasColumnType("boolean")
                        .HasColumnName("existing_target_link");

                    b.Property<string>("FinalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("final_url");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("integer")
                        .HasColumnName("http_status");

                    b.Property<DateTimeOffset?>("LastAnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_analyzed_at");

                    b.Property<string>("NormalizedUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("normalized_url");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<bool>("RequiresJavaScript")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_javascript");

                    b.Property<string>("RobotsDirectives")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("robots_directives");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CandidateSiteId");

                    b.HasIndex("ProjectId", "AnalysisStatus");

                    b.HasIndex("ProjectId", "NormalizedUrl")
                        .IsUnique();

                    b.HasIndex("ProjectId", "CreatedAt", "Id");

                    b.ToTable("candidate_pages", (string)null);
                });

            modelBuilder.Entity("BacklinkStudio.Domain.CandidateSite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("domain");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Domain")
                        .IsUnique();

                    b.ToTable("candidate_sites", (string)null);
                });

            modelBuilder.Entity("BacklinkStudio.Domain.DiscoveryQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_json");

                    b.Property<int>("MaximumResults")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_results");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("QueryText")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("query_text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CreatedAt", "Id");

                    b.ToTable("discovery_queries", null, t =>
                        {
                            t.HasCheckConstraint("ck_discovery_query_maximum_results", "maximum_results BETWEEN 1 AND 5000");
                        });
                });

            modelBuilder.Entity("BacklinkStudio.Domain.DiscoveryRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BlockedCount")
                        .HasColumnType("integer")
                        .HasColumnName("blocked_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DiscoveryQueryId")
                        .HasColumnType("uuid")
                        .HasColumnName("discovery_query_id");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("integer")
                        .HasColumnName("duplicate_count");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count");

                    b.PrimitiveCollection<string[]>("Errors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("errors");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("InvalidCount")
                        .HasColumnType("integer")
                        .HasColumnName("invalid_count");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<int>("UrlsAccepted")
                        .HasColumnType("integer")
                        .HasColumnName("urls_accepted");

                    b.Property<int>("UrlsDiscovered")
                        .HasColumnType("integer")
                        .HasColumnName("urls_discovered");

                    b.HasKey("Id");

                    b.HasIndex("DiscoveryQueryId")
                        .IsUnique();

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.HasIndex("ProjectId", "Status");

                    b.HasIndex("ProjectId", "CreatedAt", "Id");

                    b.ToTable("discovery_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_discovery_run_accepted", "urls_accepted >= 0");

                            t.HasCheckConstraint("ck_discovery_run_blocked", "blocked_count >= 0");

                            t.HasCheckConstraint("ck_discovery_run_discovered", "urls_discovered >= 0");

                            t.HasCheckConstraint("ck_discovery_run_duplicates", "duplicate_count >= 0");

                            t.HasCheckConstraint("ck_discovery_run_errors", "error_count >= 0");

                            t.HasCheckConstraint("ck_discovery_run_invalid", "invalid_count >= 0");
                        });
                });

            modelBuilder.Entity("BacklinkStudio.Domain.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource_type");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_json");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("scope");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Scope", "Key")
                        .IsUnique();

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("BacklinkStudio.Domain.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnalysisReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("analysis_reason");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("approved_by");

                    b.Property<string>("AutomationStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("automation_status");

                    b.Property<Guid>("CandidatePageId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_page_id");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("domain");

                    b.Property<DateTimeOffset>("LastAnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_analyzed_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("QualityScore")
                        .HasColumnType("integer")
                        .HasColumnName("quality_score");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CandidatePageId")
                        .IsUnique();

                    b.HasIndex("Domain");

                    b.HasIndex("ProjectId", "DetectedAt", "Id");

                    b.HasIndex("ProjectId", "QualityScore", "RiskScore");

                    b.ToTable("opportunities", null, t =>
                        {
                            t.HasCheckConstraint("ck_opportunities_quality_score", "quality_score BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_opportunities_risk_score", "risk_score BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("BacklinkStudio.Domain.OpportunityScoreReason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("explanation");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId", "Kind");

                    b.ToTable("opportunity_score_reasons", null, t =>
                        {
                            t.HasCheckConstraint("ck_opportunity_score_reason_points", "points BETWEEN -100 AND 100");
                        });
                });

            modelBuilder.Entity("BacklinkStudio.Domain.PersistentJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset?>("ClaimExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claim_expires_at");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Domain")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("domain");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<string>("LastFailureKind")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("last_failure_kind");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<DateTimeOffset?>("PauseRequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pause_requested_at");

                    b.Property<DateTimeOffset?>("PausedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paused_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("RecoveryCount")
                        .HasColumnType("integer")
                        .HasColumnName("recovery_count");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("ClaimExpiresAt")
                        .HasDatabaseName("ix_jobs_expired_claims")
                        .HasFilter("status IN ('Claimed', 'Running')");

                    b.HasIndex("CampaignId", "CompletedAt")
                        .HasDatabaseName("ix_jobs_submission_campaign_completed")
                        .HasFilter("type = 'Submission' AND status = 'Succeeded'");

                    b.HasIndex("ProjectId", "ClaimExpiresAt")
                        .HasDatabaseName("ix_jobs_active_project")
                        .HasFilter("status IN ('Claimed', 'Running')");

                    b.HasIndex("CampaignId", "Status", "ClaimExpiresAt");

                    b.HasIndex("Domain", "Status", "ClaimExpiresAt");

                    b.HasIndex("Priority", "AvailableAt", "CreatedAt")
                        .IsDescending(true, false, false)
                        .HasDatabaseName("ix_jobs_claim_ready")
                        .HasFilter("status IN ('Queued', 'RetryScheduled') AND pause_requested_at IS NULL");

                    b.HasIndex("ProjectId", "CampaignId", "CompletedAt")
                        .HasDatabaseName("ix_jobs_submission_project_campaign_completed")
                        .HasFilter("type = 'Submission' AND status = 'Succeeded'");

                    b.HasIndex("ProjectId", "CreatedAt", "Id");

                    b.HasIndex("ProjectId", "Domain", "CompletedAt")
                        .HasDatabaseName("ix_jobs_submission_project_domain_completed")
                        .HasFilter("type = 'Submission' AND status = 'Succeeded'");

                    b.HasIndex("ProjectId", "Type", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Status", "AvailableAt", "Priority", "CreatedAt");

                    b.ToTable("jobs", null, t =>
                        {
                            t.HasCheckConstraint("ck_jobs_domain", "domain IS NULL OR (char_length(domain) BETWEEN 1 AND 253 AND domain = lower(domain))");

                            t.HasCheckConstraint("ck_jobs_recovery_count", "recovery_count >= 0");
                        });
                });

            modelBuilder.Entity("BacklinkStudio.Domain.PolicyDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutomationEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("automation_enabled");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DailyActionLimit")
                        .HasColumnType("integer")
                        .HasColumnName("daily_action_limit");

                    b.Property<int>("HourlyActionLimit")
                        .HasColumnType("integer")
                        .HasColumnName("hourly_action_limit");

                    b.Property<bool>("ManualReviewRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("manual_review_required");

                    b.Property<int>("MaximumRiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_risk_score");

                    b.Property<int>("MinimumQualityScore")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_quality_score");

                    b.Property<int>("PerDomainActionLimit")
                        .HasColumnType("integer")
                        .HasColumnName("per_domain_action_limit");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("policy_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_policy_daily_limit", "daily_action_limit BETWEEN 0 AND 100000");

                            t.HasCheckConstraint("ck_policy_domain_limit", "per_domain_action_limit BETWEEN 0 AND 10000");

                            t.HasCheckConstraint("ck_policy_hourly_limit", "hourly_action_limit BETWEEN 0 AND 10000");

                            t.HasCheckConstraint("ck_policy_quality_score", "minimum_quality_score BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_policy_risk_score", "maximum_risk_score BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("BacklinkStudio.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PrimaryDomain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("primary_domain");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryDomain");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("BacklinkStudio.Domain.ProjectTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.PrimitiveCollection<string[]>("Keywords")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("keywords");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<string>("NormalizedUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("normalized_url");

                    b.Property<string>("PreferredAnchor")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("preferred_anchor");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "NormalizedUrl")
                        .IsUnique();

                    b.HasIndex("ProjectId", "CreatedAt", "Id");

                    b.ToTable("project_targets", (string)null);
                });

            modelBuilder.Entity("BacklinkStudio.Domain.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArtifactName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("artifact_name");

                    b.Property<long?>("ByteLength")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_length");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("format");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int?>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.Property<string>("Sha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sha256");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("CampaignId", "CreatedAt", "Id");

                    b.HasIndex("ProjectId", "CreatedAt", "Id");

                    b.ToTable("reports", null, t =>
                        {
                            t.HasCheckConstraint("ck_reports_byte_length", "byte_length IS NULL OR byte_length >= 0");

                            t.HasCheckConstraint("ck_reports_row_count", "row_count IS NULL OR row_count >= 0");
                        });
                });

            modelBuilder.Entity("BacklinkStudio.Domain.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActionPayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("action_payload");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("action_type");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset?>("ClaimExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claim_expires_at");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("claimed_by");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_failures");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CronExpression")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cron_expression");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("integer")
                        .HasColumnName("day_of_month");

                    b.Property<string>("DayOfWeek")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("day_of_week");

                    b.Property<int?>("IntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("interval_minutes");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("last_error");

                    b.Property<int>("LastJobCount")
                        .HasColumnType("integer")
                        .HasColumnName("last_job_count");

                    b.Property<DateTimeOffset?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<DateTimeOffset?>("LastScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_scheduled_for");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("NextRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at");

                    b.Property<DateTimeOffset?>("OneTimeAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("one_time_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("RecoveryCount")
                        .HasColumnType("integer")
                        .HasColumnName("recovery_count");

                    b.Property<string>("RecurrenceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("recurrence_type");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<TimeOnly?>("TimeOfDayUtc")
                        .HasColumnType("time without time zone")
                        .HasColumnName("time_of_day_utc");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ClaimExpiresAt");

                    b.HasIndex("ProjectId", "CreatedAt", "Id");

                    b.HasIndex("Status", "NextRunAt", "AvailableAt");

                    b.ToTable("schedules", null, t =>
                        {
                            t.HasCheckConstraint("ck_schedule_day_of_month", "day_of_month IS NULL OR day_of_month BETWEEN 1 AND 31");

                            t.HasCheckConstraint("ck_schedule_failures", "consecutive_failures >= 0");

                            t.HasCheckConstraint("ck_schedule_interval", "interval_minutes IS NULL OR interval_minutes BETWEEN 1 AND 525600");

                            t.HasCheckConstraint("ck_schedule_last_job_count", "last_job_count >= 0");

                            t.HasCheckConstraint("ck_schedule_recoveries", "recovery_count >= 0");

                            t.HasCheckConstraint("ck_schedule_timing", "(recurrence_type = 'OneTime' AND one_time_at IS NOT NULL AND interval_minutes IS NULL AND time_of_day_utc IS NULL AND day_of_week IS NULL AND day_of_month IS NULL AND cron_expression IS NULL) OR (recurrence_type = 'Interval' AND one_time_at IS NULL AND interval_minutes IS NOT NULL AND time_of_day_utc IS NULL AND day_of_week IS NULL AND day_of_month IS NULL AND cron_expression IS NULL) OR (recurrence_type = 'Daily' AND one_time_at IS NULL AND interval_minutes IS NULL AND time_of_day_utc IS NOT NULL AND day_of_week IS NULL AND day_of_month IS NULL AND cron_expression IS NULL) OR (recurrence_type = 'Weekly' AND one_time_at IS NULL AND interval_minutes IS NULL AND time_of_day_utc IS NOT NULL AND day_of_week IS NOT NULL AND day_of_month IS NULL AND cron_expression IS NULL) OR (recurrence_type = 'Monthly' AND one_time_at IS NULL AND interval_minutes IS NULL AND time_of_day_utc IS NOT NULL AND day_of_week IS NULL AND day_of_month IS NOT NULL AND cron_expression IS NULL) OR (recurrence_type = 'Cron' AND one_time_at IS NULL AND interval_minutes IS NULL AND time_of_day_utc IS NULL AND day_of_week IS NULL AND day_of_month IS NULL AND cron_expression IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("BacklinkStudio.Domain.SubmissionAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Adapter")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("adapter");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_number");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("external_reference");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("integer")
                        .HasColumnName("http_status");

                    b.Property<string>("Result")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("result");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("SubmissionJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_job_id");

                    b.HasKey("Id");

                    b.HasIndex("SubmissionJobId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("submission_attempts", null, t =>
                        {
                            t.HasCheckConstraint("ck_submission_attempt_number", "attempt_number > 0");
                        });
                });

            modelBuilder.Entity("BacklinkStudio.Domain.SubmissionJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid>("CampaignOpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_opportunity_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PersistentJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("persistent_job_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CampaignOpportunityId")
                        .IsUnique();

                    b.HasIndex("PersistentJobId")
                        .IsUnique();

                    b.HasIndex("ProjectId");

                    b.HasIndex("CampaignId", "CreatedAt", "Id");

                    b.ToTable("submission_jobs", (string)null);
                });

            modelBuilder.Entity("BacklinkStudio.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BacklinkStudio.Domain.VerificationCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Anchor")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("anchor");

                    b.Property<Guid>("BacklinkId")
                        .HasColumnType("uuid")
                        .HasColumnName("backlink_id");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_at");

                    b.Property<int>("DurationMilliseconds")
                        .HasColumnType("integer")
                        .HasColumnName("duration_milliseconds");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("error");

                    b.Property<bool>("Found")
                        .HasColumnType("boolean")
                        .HasColumnName("found");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("integer")
                        .HasColumnName("http_status");

                    b.PrimitiveCollection<string[]>("Rel")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("rel");

                    b.HasKey("Id");

                    b.HasIndex("BacklinkId", "CheckedAt", "Id");

                    b.ToTable("verification_checks", null, t =>
                        {
                            t.HasCheckConstraint("ck_verification_duration", "duration_milliseconds >= 0");
                        });
                });

            modelBuilder.Entity("BacklinkStudio.Infrastructure.Persistence.DomainRateLimitRow", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("scope_key");

                    b.Property<string>("Domain")
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("domain");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset>("NextAllowedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_allowed_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ScopeKey", "Domain");

                    b.HasIndex("NextAllowedAt");

                    b.HasIndex("ProjectId");

                    b.ToTable("domain_rate_limits", null, t =>
                        {
                            t.HasCheckConstraint("ck_domain_rate_limit_domain", "char_length(domain) BETWEEN 1 AND 253 AND domain = lower(domain)");
                        });
                });

            modelBuilder.Entity("BacklinkStudio.Infrastructure.Persistence.WorkerHeartbeatRow", b =>
                {
                    b.Property<string>("WorkerId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("worker_id");

                    b.Property<int>("ActiveJobs")
                        .HasColumnType("integer")
                        .HasColumnName("active_jobs");

                    b.Property<int>("BufferSize")
                        .HasColumnType("integer")
                        .HasColumnName("buffer_size");

                    b.Property<int>("Concurrency")
                        .HasColumnType("integer")
                        .HasColumnName("concurrency");

                    b.Property<DateTimeOffset>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("machine_name");

                    b.Property<int>("ProcessId")
                        .HasColumnType("integer")
                        .HasColumnName("process_id");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<DateTimeOffset?>("StoppedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("stopped_at");

                    b.HasKey("WorkerId");

                    b.HasIndex("StoppedAt", "LastHeartbeatAt");

                    b.ToTable("worker_heartbeats", null, t =>
                        {
                            t.HasCheckConstraint("ck_worker_heartbeat_active", "active_jobs BETWEEN 0 AND concurrency");

                            t.HasCheckConstraint("ck_worker_heartbeat_buffer", "buffer_size BETWEEN 1 AND 1000");

                            t.HasCheckConstraint("ck_worker_heartbeat_concurrency", "concurrency BETWEEN 1 AND 32");
                        });
                });

            modelBuilder.Entity("BacklinkStudio.Domain.AgentCredential", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.Backlink", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BacklinkStudio.Domain.SubmissionJob", null)
                        .WithOne()
                        .HasForeignKey("BacklinkStudio.Domain.Backlink", "SubmissionJobId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("BacklinkStudio.Domain.BlocklistEntry", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.Campaign", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.CampaignOpportunity", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BacklinkStudio.Domain.Opportunity", null)
                        .WithMany()
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.CampaignTarget", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BacklinkStudio.Domain.ProjectTarget", null)
                        .WithMany()
                        .HasForeignKey("ProjectTargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.CandidatePage", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.CandidateSite", null)
                        .WithMany()
                        .HasForeignKey("CandidateSiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.CandidateSite", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.DiscoveryQuery", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.DiscoveryRun", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.DiscoveryQuery", null)
                        .WithMany()
                        .HasForeignKey("DiscoveryQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BacklinkStudio.Domain.PersistentJob", null)
                        .WithOne()
                        .HasForeignKey("BacklinkStudio.Domain.DiscoveryRun", "JobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.Opportunity", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.CandidatePage", null)
                        .WithMany()
                        .HasForeignKey("CandidatePageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.OpportunityScoreReason", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Opportunity", null)
                        .WithMany("ScoreReasons")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.PersistentJob", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.PolicyDefinition", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithOne()
                        .HasForeignKey("BacklinkStudio.Domain.PolicyDefinition", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.ProjectTarget", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.Report", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BacklinkStudio.Domain.PersistentJob", null)
                        .WithOne()
                        .HasForeignKey("BacklinkStudio.Domain.Report", "JobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.Schedule", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.SubmissionAttempt", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.SubmissionJob", null)
                        .WithMany()
                        .HasForeignKey("SubmissionJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.SubmissionJob", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Campaign", null)
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BacklinkStudio.Domain.CampaignOpportunity", null)
                        .WithOne()
                        .HasForeignKey("BacklinkStudio.Domain.SubmissionJob", "CampaignOpportunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BacklinkStudio.Domain.PersistentJob", null)
                        .WithOne()
                        .HasForeignKey("BacklinkStudio.Domain.SubmissionJob", "PersistentJobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.VerificationCheck", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Backlink", null)
                        .WithMany()
                        .HasForeignKey("BacklinkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Infrastructure.Persistence.DomainRateLimitRow", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.Opportunity", b =>
                {
                    b.Navigation("ScoreReasons");
                });
#pragma warning restore 612, 618
        }
    }
}
