// <auto-generated />
using System;
using BacklinkStudio.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BacklinkStudio.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BacklinkStudioDbContext))]
    [Migration("20260818164119_AddDiscoveryFoundation")]
    partial class AddDiscoveryFoundation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BacklinkStudio.Domain.AgentCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<byte[]>("KeyHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key_hash");

                    b.Property<byte[]>("KeySalt")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("key_salt");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("LookupHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("lookup_hash");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.PrimitiveCollection<string[]>("Scopes")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("scopes");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("LookupHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("agent_credentials", (string)null);
                });

            modelBuilder.Entity("BacklinkStudio.Domain.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_id");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<Guid?>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<string>("InputSummary")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("input_summary");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("operation");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("request_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("result");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("source_address");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("ProjectId", "Timestamp");

                    b.ToTable("audit_events", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_input_summary_length", "length(input_summary) <= 2000");
                        });
                });

            modelBuilder.Entity("BacklinkStudio.Domain.BlocklistEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("MatchType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("match_type");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CreatedAt", "Id");

                    b.HasIndex("ProjectId", "MatchType", "Value")
                        .IsUnique();

                    b.ToTable("blocklist_entries", (string)null);
                });

            modelBuilder.Entity("BacklinkStudio.Domain.CandidatePage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnalysisError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("analysis_error");

                    b.Property<string>("AnalysisStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("analysis_status");

                    b.Property<Guid>("CandidateSiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_site_id");

                    b.Property<string>("CanonicalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("canonical_url");

                    b.Property<string>("Cms")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cms");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.PrimitiveCollection<string[]>("EligibleSignals")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("eligible_signals");

                    b.Property<bool>("ExistingTargetLink")
                        .HasColumnType("boolean")
                        .HasColumnName("existing_target_link");

                    b.Property<string>("FinalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("final_url");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("integer")
                        .HasColumnName("http_status");

                    b.Property<DateTimeOffset?>("LastAnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_analyzed_at");

                    b.Property<string>("NormalizedUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("normalized_url");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<bool>("RequiresJavaScript")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_javascript");

                    b.Property<string>("RobotsDirectives")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("robots_directives");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CandidateSiteId");

                    b.HasIndex("ProjectId", "AnalysisStatus");

                    b.HasIndex("ProjectId", "NormalizedUrl")
                        .IsUnique();

                    b.HasIndex("ProjectId", "CreatedAt", "Id");

                    b.ToTable("candidate_pages", (string)null);
                });

            modelBuilder.Entity("BacklinkStudio.Domain.CandidateSite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("domain");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Domain")
                        .IsUnique();

                    b.ToTable("candidate_sites", (string)null);
                });

            modelBuilder.Entity("BacklinkStudio.Domain.DiscoveryQuery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_json");

                    b.Property<int>("MaximumResults")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_results");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("QueryText")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("query_text");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "CreatedAt", "Id");

                    b.ToTable("discovery_queries", null, t =>
                        {
                            t.HasCheckConstraint("ck_discovery_query_maximum_results", "maximum_results BETWEEN 1 AND 5000");
                        });
                });

            modelBuilder.Entity("BacklinkStudio.Domain.DiscoveryRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("BlockedCount")
                        .HasColumnType("integer")
                        .HasColumnName("blocked_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DiscoveryQueryId")
                        .HasColumnType("uuid")
                        .HasColumnName("discovery_query_id");

                    b.Property<int>("DuplicateCount")
                        .HasColumnType("integer")
                        .HasColumnName("duplicate_count");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count");

                    b.PrimitiveCollection<string[]>("Errors")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("errors");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("InvalidCount")
                        .HasColumnType("integer")
                        .HasColumnName("invalid_count");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<int>("UrlsAccepted")
                        .HasColumnType("integer")
                        .HasColumnName("urls_accepted");

                    b.Property<int>("UrlsDiscovered")
                        .HasColumnType("integer")
                        .HasColumnName("urls_discovered");

                    b.HasKey("Id");

                    b.HasIndex("DiscoveryQueryId")
                        .IsUnique();

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.HasIndex("ProjectId", "Status");

                    b.HasIndex("ProjectId", "CreatedAt", "Id");

                    b.ToTable("discovery_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_discovery_run_accepted", "urls_accepted >= 0");

                            t.HasCheckConstraint("ck_discovery_run_blocked", "blocked_count >= 0");

                            t.HasCheckConstraint("ck_discovery_run_discovered", "urls_discovered >= 0");

                            t.HasCheckConstraint("ck_discovery_run_duplicates", "duplicate_count >= 0");

                            t.HasCheckConstraint("ck_discovery_run_errors", "error_count >= 0");

                            t.HasCheckConstraint("ck_discovery_run_invalid", "invalid_count >= 0");
                        });
                });

            modelBuilder.Entity("BacklinkStudio.Domain.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource_type");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_json");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("scope");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Scope", "Key")
                        .IsUnique();

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("BacklinkStudio.Domain.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnalysisReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("analysis_reason");

                    b.Property<string>("AutomationStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("automation_status");

                    b.Property<Guid>("CandidatePageId")
                        .HasColumnType("uuid")
                        .HasColumnName("candidate_page_id");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("domain");

                    b.Property<DateTimeOffset>("LastAnalyzedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_analyzed_at");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<int>("QualityScore")
                        .HasColumnType("integer")
                        .HasColumnName("quality_score");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("source_url");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("CandidatePageId")
                        .IsUnique();

                    b.HasIndex("Domain");

                    b.HasIndex("ProjectId", "DetectedAt", "Id");

                    b.HasIndex("ProjectId", "QualityScore", "RiskScore");

                    b.ToTable("opportunities", null, t =>
                        {
                            t.HasCheckConstraint("ck_opportunities_quality_score", "quality_score BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_opportunities_risk_score", "risk_score BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("BacklinkStudio.Domain.OpportunityScoreReason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("explanation");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId", "Kind");

                    b.ToTable("opportunity_score_reasons", null, t =>
                        {
                            t.HasCheckConstraint("ck_opportunity_score_reason_points", "points BETWEEN -100 AND 100");
                        });
                });

            modelBuilder.Entity("BacklinkStudio.Domain.PersistentJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<Guid?>("CampaignId")
                        .HasColumnType("uuid")
                        .HasColumnName("campaign_id");

                    b.Property<DateTimeOffset?>("ClaimExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claim_expires_at");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("claimed_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.Property<string>("WorkerId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("worker_id");

                    b.HasKey("Id");

                    b.HasIndex("ClaimExpiresAt");

                    b.HasIndex("ProjectId", "CreatedAt", "Id");

                    b.HasIndex("ProjectId", "Type", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("Status", "AvailableAt", "Priority", "CreatedAt");

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("BacklinkStudio.Domain.PolicyDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutomationEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("automation_enabled");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("DailyActionLimit")
                        .HasColumnType("integer")
                        .HasColumnName("daily_action_limit");

                    b.Property<int>("HourlyActionLimit")
                        .HasColumnType("integer")
                        .HasColumnName("hourly_action_limit");

                    b.Property<bool>("ManualReviewRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("manual_review_required");

                    b.Property<int>("MaximumRiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("maximum_risk_score");

                    b.Property<int>("MinimumQualityScore")
                        .HasColumnType("integer")
                        .HasColumnName("minimum_quality_score");

                    b.Property<int>("PerDomainActionLimit")
                        .HasColumnType("integer")
                        .HasColumnName("per_domain_action_limit");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("policy_definitions", null, t =>
                        {
                            t.HasCheckConstraint("ck_policy_daily_limit", "daily_action_limit BETWEEN 0 AND 100000");

                            t.HasCheckConstraint("ck_policy_domain_limit", "per_domain_action_limit BETWEEN 0 AND 10000");

                            t.HasCheckConstraint("ck_policy_hourly_limit", "hourly_action_limit BETWEEN 0 AND 10000");

                            t.HasCheckConstraint("ck_policy_quality_score", "minimum_quality_score BETWEEN 0 AND 100");

                            t.HasCheckConstraint("ck_policy_risk_score", "maximum_risk_score BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("BacklinkStudio.Domain.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PrimaryDomain")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("primary_domain");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryDomain");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("BacklinkStudio.Domain.ProjectTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.PrimitiveCollection<string[]>("Keywords")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("keywords");

                    b.Property<string>("Label")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<string>("NormalizedUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("normalized_url");

                    b.Property<string>("PreferredAnchor")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("preferred_anchor");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "NormalizedUrl")
                        .IsUnique();

                    b.HasIndex("ProjectId", "CreatedAt", "Id");

                    b.ToTable("project_targets", (string)null);
                });

            modelBuilder.Entity("BacklinkStudio.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("BacklinkStudio.Domain.AgentCredential", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.BlocklistEntry", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.CandidatePage", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.CandidateSite", null)
                        .WithMany()
                        .HasForeignKey("CandidateSiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.CandidateSite", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.DiscoveryQuery", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.DiscoveryRun", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.DiscoveryQuery", null)
                        .WithMany()
                        .HasForeignKey("DiscoveryQueryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BacklinkStudio.Domain.PersistentJob", null)
                        .WithOne()
                        .HasForeignKey("BacklinkStudio.Domain.DiscoveryRun", "JobId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.Opportunity", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.CandidatePage", null)
                        .WithMany()
                        .HasForeignKey("CandidatePageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.OpportunityScoreReason", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Opportunity", null)
                        .WithMany("ScoreReasons")
                        .HasForeignKey("OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.PersistentJob", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.PolicyDefinition", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithOne()
                        .HasForeignKey("BacklinkStudio.Domain.PolicyDefinition", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.ProjectTarget", b =>
                {
                    b.HasOne("BacklinkStudio.Domain.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BacklinkStudio.Domain.Opportunity", b =>
                {
                    b.Navigation("ScoreReasons");
                });
#pragma warning restore 612, 618
        }
    }
}
