<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\BacklinkStudio.Domain\BacklinkStudio.Domain.csproj" />
    <ProjectReference Include="..\BacklinkStudio.Application\BacklinkStudio.Application.csproj" />
  </ItemGroup>
  <ItemGroup><PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" /></ItemGroup>
</Project>
